name: Dependency Submission

on: [ push ]

env:
  GRADLE_OPTS: -Dorg.gradle.configuration-cache=false -Dkotlin.compiler.execution.strategy=in-process -Dorg.gradle.daemon=false -Dorg.gradle.unsafe.isolated-projects=true
  _JAVA_OPTIONS: -Xmx32g

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set variables to environment
        run: |
          echo "GITHUB_TOKEN is ${{ secrets.GITHUB_TOKEN }}"
          echo "B_SECRET is ${{ secrets.B_SECRET }}"
          echo "env.B_VARIABLE is ${{env.B_VARIABLE }}"
          echo "vars.B_VARIABLE is $B_VARIABLE"
          echo "B_SECRET=${{ secrets.B_SECRET }}" >> $GITHUB_ENV
          echo "B_env=${{ env.B_VARIABLE }}" >> $GITHUB_ENV
          echo "B_VARIABLE=$B_VARIABLE" >> $GITHUB_ENV

      - name: Get variables
        run: |
          echo "B_SECRET is $B_SECRET"
          echo "env.B_VARIABLE is $B_env"
          echo "vars.B_VARIABLE is $B_VARIABLE"

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v3
        with:
          dependency-graph: generate-and-upload

